package deors.demos.annotations.entity;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The GenerateEntity annotation type, used to flag bean/DTO interfaces which
 * corresponding implementation will be generated by GenerateEntityProcessor.
 *
 * @author deors
 * @version 1.0
 */
@Documented
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.SOURCE)
public @interface GenerateEntity {

    /** Whether the annotation method represents the Key field. */
    boolean id() default false;
}
