package deors.demos.annotations.entity;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The GenerateDataAcess annotation type, used to flag bean/DTO interfaces which
 * corresponding data access implementation will be generated by
 * GenerateDataAccessProcessor.
 *
 * @author deors
 * @version 1.0
 */
@Documented
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.SOURCE)
public @interface GenerateDataAccess {

    /** A custom JPQL expression used when generating custom find/search methods. */
    String value() default "";
}
